
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anthonymcgarry
 */
public class AdminSetupForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminSetupForm
     */
    public AdminSetupForm() {
        initComponents();
        this.setLocationRelativeTo(null); //Set form to the center of the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        onSetupProgrammes = new javax.swing.JButton();
        onSetupStudent = new javax.swing.JButton();
        onLogout = new javax.swing.JButton();
        onSetupTutor = new javax.swing.JButton();
        onSetupModules = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Zone");

        onSetupProgrammes.setText("Setup Programmes");
        onSetupProgrammes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSetupProgrammesActionPerformed(evt);
            }
        });

        onSetupStudent.setText("Setup Students");
        onSetupStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSetupStudentActionPerformed(evt);
            }
        });

        onLogout.setBackground(new java.awt.Color(153, 0, 51));
        onLogout.setText("Logout");
        onLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLogoutActionPerformed(evt);
            }
        });

        onSetupTutor.setText("Setup Tutors");
        onSetupTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSetupTutorActionPerformed(evt);
            }
        });

        onSetupModules.setText("Setup Modules");
        onSetupModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSetupModulesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(onLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(onSetupProgrammes, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(onSetupTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onSetupStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(onSetupModules, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onSetupStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onSetupTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onSetupProgrammes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onSetupModules, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(onLogout)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This Form is used to control the on logout button action 
     * @param evt 
     */
    private void onLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLogoutActionPerformed
        // An option pane will populate asking the user if they are sure they want to logout
        // If they do then the user is navigated back to the login form
        int option = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if(option == 1) return;
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_onLogoutActionPerformed
    /**
     * This method navigates the user to the Programme form if setup programme button is pressed 
     * @param evt 
     */
    private void onSetupProgrammesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSetupProgrammesActionPerformed
        // TODO add your handling code here:
        ProgramForm form = new ProgramForm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose(); 
        
        
    }//GEN-LAST:event_onSetupProgrammesActionPerformed
    /**
     * This method navigates the user to the Student form if setup student button is pressed 
     * @param evt 
     */
    private void onSetupStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSetupStudentActionPerformed
        // TODO add your handling code here:
        StudentForm sf = new StudentForm();
        sf.setVisible(true);
        sf.pack();
        sf.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_onSetupStudentActionPerformed
    /**
     * This method navigates the user to the Tutor form if setup tutor button is pressed 
     * @param evt 
     */
    private void onSetupTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSetupTutorActionPerformed
        // TODO add your handling code here:
        TutorForm tf = new TutorForm();
        tf.setVisible(true);
        tf.pack();
        tf.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_onSetupTutorActionPerformed
    /**
     * This method navigates the user to the Module form if setup module button is pressed 
     * @param evt 
     */
    private void onSetupModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSetupModulesActionPerformed
        // TODO add your handling code here:
        ModuleForm form = new ModuleForm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_onSetupModulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSetupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSetupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSetupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSetupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSetupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton onLogout;
    private javax.swing.JButton onSetupModules;
    private javax.swing.JButton onSetupProgrammes;
    private javax.swing.JButton onSetupStudent;
    private javax.swing.JButton onSetupTutor;
    // End of variables declaration//GEN-END:variables
}
