
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Module;
import student.attendance.JDBConnection.CISConnection;
import student.attendance.ModuleList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anthonymcgarry
 */
public class ModuleForm extends javax.swing.JFrame {
    private static DefaultTableModel model; //sets the table model
    private ModuleList list = new ModuleList(); //module list to store the modules
    private int level = 1; //module level
    private int semester = 1;// module semester
    CISConnection cis = new CISConnection("cis4005");// Establishes connection to the DB
    
    /**
     * Creates new form ModuleForm
     */
    public ModuleForm() {
        initComponents();
        this.setLocationRelativeTo(null);//center from
        getModules();// get the modules from the DB
    }
    
    public void getModules(){
        cis.getModuleList(list); //Get the modules from the DB
        model = (DefaultTableModel) moduleTable.getModel(); // Set the model to match JTable modle
        for(int i = 0; i < list.Size(); i++){
           //For each module in the moduleList pass the module object to the inserTableRow method
           insertTableRow(list.get(i));
        }
    }
    /**
     * This method renders a new row for each module object 
     * that is passed to this method and renders the data in their respected column
     * @param m get the module object
     */
    private void insertTableRow(Module m){
        Object rowData[] = new Object[5];
        rowData[0] = m.getModuleCode();
        rowData[1] = m.getModuleTitle();
        rowData[2] = m.getModuleCredit();
        rowData[3] = m.getModuleLevel();
        rowData[4] = m.getModuleSemester();
        model.addRow(rowData);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        moduleTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldModuleTitle = new javax.swing.JFormattedTextField();
        textFieldModuleCode = new javax.swing.JFormattedTextField();
        textFieldModuleCredit = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxModuleLevel = new javax.swing.JComboBox<>();
        comboBoxModuleSemester = new javax.swing.JComboBox<>();
        addModule = new javax.swing.JButton();
        removeModule = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Module Portal");

        moduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Module Code", "Title", "Credit", "Level", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(moduleTable);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Module Code:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Module Title:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Module Credit:");

        textFieldModuleTitle.setBackground(new java.awt.Color(255, 255, 255));
        textFieldModuleTitle.setForeground(new java.awt.Color(0, 0, 0));

        textFieldModuleCode.setBackground(new java.awt.Color(255, 255, 255));
        textFieldModuleCode.setForeground(new java.awt.Color(0, 0, 0));

        textFieldModuleCredit.setBackground(new java.awt.Color(255, 255, 255));
        textFieldModuleCredit.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Module Level:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Module Semester:");

        comboBoxModuleLevel.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxModuleLevel.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxModuleLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        comboBoxModuleLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModuleLevelActionPerformed(evt);
            }
        });

        comboBoxModuleSemester.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxModuleSemester.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxModuleSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2" }));
        comboBoxModuleSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModuleSemesterActionPerformed(evt);
            }
        });

        addModule.setText("Add Module");
        addModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModuleActionPerformed(evt);
            }
        });

        removeModule.setText("Remove Module");
        removeModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeModuleActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(153, 0, 51));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldModuleCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(216, 216, 216))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldModuleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxModuleSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(52, 52, 52)
                                        .addComponent(comboBoxModuleLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeModule, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addModule, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(textFieldModuleCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(500, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxModuleLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldModuleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(comboBoxModuleSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldModuleCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addModule)
                    .addComponent(cancelButton))
                .addGap(18, 18, 18)
                .addComponent(removeModule)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(365, 365, 365)
                    .addComponent(textFieldModuleCode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * addModuleActionPerformed module takes all the input fields and creates a new module
     * which is then added to the module list and rendered in the JTable and submitted to DB
     * After successfully adding a new module all the fields, level and semester are set back to default values.
     * @param evt 
     */
    private void addModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModuleActionPerformed
        // TODO add your handling code here:
        String code = textFieldModuleCode.getText();
        String title = textFieldModuleTitle.getText();
        String credit = textFieldModuleCredit.getText();
        if(code == null || code.equals("") || title == null || title.equals("") || credit == null || credit.equals("") ){
            JOptionPane.showMessageDialog(null, "Every field requires an input", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!isNumeric(credit)){
            JOptionPane.showMessageDialog(null, "Credit must be a number", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int newId = list.get(list.Size() -1).getModuleId();
        if (newId >= 1) {
          newId++;
        } else {
           newId = 1;
        }
        int id = newId;
        int numberCredit = Integer.parseInt(credit);
        Module m = new Module(id, title, numberCredit, code, level, semester);
        cis.insertModule(m);
        list.add(m);
        insertTableRow(m);
        textFieldModuleCode.setText("");
        textFieldModuleTitle.setText("");
        textFieldModuleCredit.setText("");
        comboBoxModuleLevel.setSelectedIndex(0);
        comboBoxModuleSemester.setSelectedIndex(0);
        level = 1;
        semester = 1;
       
        
    }//GEN-LAST:event_addModuleActionPerformed
    /**
     * removeModuleActionPerformed requires the user to select module from the JTable
     * once selected it is then checks to see if the given module is available in the moduleList
     * if this is true then the module is removed from the list, JTable and also the DB
     * @param evt 
     */
    private void removeModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeModuleActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = moduleTable.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select a module", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object moduleCode = moduleTable.getValueAt(selectedRowIndex, 0);
        String code = moduleCode.toString();
        for(int i = 0; i < list.Size(); i++){
            Module m = list.get(i);
            if(code == m.getModuleCode()){
               list.remove(m);
               cis.removeModule(code);
               model.removeRow(selectedRowIndex);
               System.out.println("REMOVE");
            }
        }
        
    }//GEN-LAST:event_removeModuleActionPerformed
    /**
     * This method set the level depending on which option was selected by the user
     * @param evt 
     */
    private void comboBoxModuleLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModuleLevelActionPerformed
        // TODO add your handling code here:
        if(comboBoxModuleLevel.getSelectedItem().equals("Level 1")){
            this.level = 1;
        }
        else if(comboBoxModuleLevel.getSelectedItem().equals("Level 2")){
            this.level = 2;
        }
        else if(comboBoxModuleLevel.getSelectedItem().equals("Level 3")){
            this.level = 3;
        }
    }//GEN-LAST:event_comboBoxModuleLevelActionPerformed
    /**
     * This method set the semester depending on which option was selected by the user
     * @param evt 
     */
    private void comboBoxModuleSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModuleSemesterActionPerformed
        // TODO add your handling code here:
        if(comboBoxModuleSemester.getSelectedItem().equals("Semester 1")){
            this.semester = 1;
        }
        else if(comboBoxModuleSemester.getSelectedItem().equals("Semester 2")){
            this.semester = 2;
        }
    }//GEN-LAST:event_comboBoxModuleSemesterActionPerformed
    /**
     * This method returns the user back to the admin form
     * @param evt 
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        AdminSetupForm form = new AdminSetupForm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /**
     * 
     * @param s Check if a string is a number
     * This method is to make sure the credit is a number
     * @return 
     */
    public boolean isNumeric(String s) {  
    return s != null && s.matches("[-+]?\\d*\\.?\\d+");  
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModule;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> comboBoxModuleLevel;
    private javax.swing.JComboBox<String> comboBoxModuleSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable moduleTable;
    private javax.swing.JButton removeModule;
    private javax.swing.JFormattedTextField textFieldModuleCode;
    private javax.swing.JFormattedTextField textFieldModuleCredit;
    private javax.swing.JFormattedTextField textFieldModuleTitle;
    // End of variables declaration//GEN-END:variables
}
